[package]
name = "layground"
version = "0.1.0"
edition = "2021"

[lints.clippy]
missing_safety_doc = "allow"

[dependencies]
widestring = "1.1.0"
windows = { version = "0.58.0", features = [
    "Win32",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
] }
